from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol


class AIProvider(Protocol):
    name: str

    @property
    def configured(self) -> bool:
        ...

    def generate(self, message: str, supporting_data: dict[str, Any]) -> str:
        ...


@dataclass(frozen=True)
class SarvamAIProvider:
    api_key: str | None
    name: str = "sarvam"

    @property
    def configured(self) -> bool:
        return bool(self.api_key and self.api_key.strip())

    def generate(self, message: str, supporting_data: dict[str, Any]) -> str:
        raise AIProviderUnavailable("Sarvam text generation is not configured for this backend yet.")


@dataclass(frozen=True)
class DeterministicAIProvider:
    name: str = "deterministic"

    @property
    def configured(self) -> bool:
        return True

    def generate(self, message: str, supporting_data: dict[str, Any]) -> str:
        raise AIProviderUnavailable("Deterministic responses are generated by the copilot service templates.")


class AIProviderUnavailable(RuntimeError):
    pass


def get_ai_provider(provider_name: str | None, sarvam_api_key: str | None) -> AIProvider:
    normalized = (provider_name or "sarvam").strip().casefold()
    if normalized == "sarvam":
        return SarvamAIProvider(sarvam_api_key)
    return DeterministicAIProvider()
