import type { ReactNode } from 'react'; import { Pressable, StyleSheet, Text, View } from 'react-native'; import { colors, radius, spacing } from '../constants/theme';
export function AppHeader({title,subtitle}:{title:string;subtitle?:string}) { return <View style={s.header}><Text style={s.title}>{title}</Text>{subtitle&&<Text style={s.subtitle}>{subtitle}</Text>}</View>; }
export function MetricCard({label,value,accent='blue'}:{label:string;value:string;accent?:'blue'|'green'}) { return <View style={[s.metric,accent==='green'&&s.green]}><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{value}</Text><Text style={s.preview}>Awaiting live data</Text></View>; }
export function InsightCard({title,children}:{title:string;children:ReactNode}) { return <View style={s.card}><Text style={s.cardTitle}>{title}</Text><Text style={s.body}>{children}</Text></View>; }
export function AlertCard({title,children,tone='warning'}:{title:string;children:ReactNode;tone?:'warning'|'danger'|'success'}) { return <View style={[s.alert,s[tone]]}><Text style={s.cardTitle}>{title}</Text><Text style={s.body}>{children}</Text></View>; }
export function PrimaryButton({label,onPress}:{label:string;onPress?:()=>void}) { return <Pressable accessibilityRole="button" onPress={onPress} style={s.primary}><Text style={s.primaryText}>{label}</Text></Pressable>; }
export function SecondaryButton({label,onPress}:{label:string;onPress?:()=>void}) { return <Pressable accessibilityRole="button" onPress={onPress} style={s.secondary}><Text style={s.secondaryText}>{label}</Text></Pressable>; }
export function EmptyState({message}:{message:string}) { return <View style={s.empty}><Text style={s.emptyTitle}>No live data yet</Text><Text style={s.body}>{message}</Text></View>; }
export function ErrorState({message}:{message:string}) { return <View style={[s.empty,s.error]}><Text style={s.cardTitle}>Couldn’t load data</Text><Text style={s.body}>{message}</Text></View>; }
const s=StyleSheet.create({header:{paddingHorizontal:spacing.lg,paddingTop:spacing.lg,paddingBottom:spacing.md},title:{color:colors.text,fontSize:27,fontWeight:'800'},subtitle:{color:colors.muted,fontSize:15,marginTop:4},card:{backgroundColor:colors.surface,borderRadius:radius.md,padding:spacing.md,borderWidth:1,borderColor:colors.border},cardTitle:{color:colors.text,fontWeight:'700',fontSize:16,marginBottom:6},body:{color:colors.muted,fontSize:14,lineHeight:20},metric:{backgroundColor:colors.blueSoft,borderRadius:radius.md,padding:spacing.md,flex:1,minHeight:112},green:{backgroundColor:'#EAF7F0'},metricLabel:{color:colors.muted,fontSize:13,fontWeight:'600'},metricValue:{color:colors.text,fontSize:25,fontWeight:'800',marginTop:8},preview:{color:colors.muted,fontSize:11,marginTop:4},alert:{padding:spacing.md,borderRadius:radius.md,borderWidth:1},warning:{backgroundColor:'#FFF8E6',borderColor:'#F3D98A'},danger:{backgroundColor:'#FFF0F0',borderColor:'#F1B6B6'},success:{backgroundColor:'#EAF7F0',borderColor:'#AEDCC2'},primary:{minHeight:52,borderRadius:radius.sm,justifyContent:'center',alignItems:'center',backgroundColor:colors.primary,paddingHorizontal:spacing.md},primaryText:{color:'#FFF',fontWeight:'800',fontSize:16},secondary:{minHeight:52,borderRadius:radius.sm,justifyContent:'center',alignItems:'center',borderWidth:1,borderColor:colors.primary,paddingHorizontal:spacing.md},secondaryText:{color:colors.primary,fontWeight:'800',fontSize:16},empty:{backgroundColor:colors.surface,borderRadius:radius.md,padding:spacing.lg,alignItems:'center',borderWidth:1,borderColor:colors.border},emptyTitle:{color:colors.text,fontSize:16,fontWeight:'700',marginBottom:6},error:{borderColor:'#F1B6B6'}});
