import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react';
import { ActivityIndicator, Pressable, RefreshControl, ScrollView, StyleSheet, Text, View } from 'react-native';
import { AppHeader, PrimaryButton } from '../components/ui';
import { colors, radius, spacing } from '../constants/theme';
import { api } from '../services/api';
import type { ForecastPoint, ForecastResponse } from '../types/business';

type LoadState = 'loading' | 'success' | 'empty' | 'error';
type Horizon = 7 | 14 | 30;
const horizons: Horizon[] = [7, 14, 30];
const money = (value?: number) => value === undefined ? '--' : `₹${Math.round(value).toLocaleString('en-IN')}`;

export function DemandForecastScreen() {
  const [horizon, setHorizon] = useState<Horizon>(7);
  const [state, setState] = useState<LoadState>('loading');
  const [refreshing, setRefreshing] = useState(false);
  const [forecast, setForecast] = useState<ForecastResponse>();
  const load = useCallback(async (isRefresh = false) => { if (isRefresh) setRefreshing(true); else setState('loading'); try { const response = await api.getForecast(horizon); setForecast(response); setState(response.forecast.length ? 'success' : 'empty'); } catch { setState('error'); } finally { setRefreshing(false); } }, [horizon]);
  useEffect(() => { void load(); }, [load]);
  const change = useMemo(() => forecast ? changeAgainstHistory(forecast.historical, forecast.forecast) : undefined, [forecast]);

  if (state === 'loading') return <ForecastState><ActivityIndicator color={colors.primary} size="large" /><Text style={s.muted}>Loading forecast…</Text></ForecastState>;
  if (state === 'error') return <StateMessage title="Forecast data is temporarily unavailable." button="Retry" onPress={() => void load()} />;
  if (state === 'empty') return <StateMessage title="No forecast is available yet." message={forecast?.message} button="Retry" onPress={() => void load()} />;
  return <ScrollView contentContainerStyle={s.page} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => void load(true)} tintColor={colors.primary} />}><AppHeader title="Demand Forecast" subtitle="Plan your stock before demand arrives." /><View style={s.body}>
    <View style={s.periods}>{horizons.map(item => <Pressable key={item} accessibilityRole="button" onPress={() => setHorizon(item)} style={[s.period, horizon === item && s.periodActive]}><Text style={[s.periodText, horizon === item && s.periodTextActive]}>{item} days</Text></Pressable>)}</View>
    <View style={s.summary}><Text style={s.kicker}>FORECAST SUMMARY</Text><Text style={s.bigValue}>{forecast?.summary?.expected_units ?? '--'} units</Text><Text style={s.muted}>Expected demand over the next {horizon} days</Text><View style={s.summaryRows}><Summary label="Expected sales" value={money(forecast?.summary?.expected_revenue)} /><Summary label="Change vs previous period" value={change === undefined ? '--' : `${change >= 0 ? '+' : ''}${change}%`} positive={change !== undefined && change >= 0} /></View></View>
    <Text style={s.section}>Demand trend</Text><TrendChart historical={forecast!.historical} future={forecast!.forecast} /><Text style={s.chartNote}>Blue: historical demand · Green: forecast demand</Text>
    <Text style={s.section}>Products to Watch</Text><View style={s.card}><Text style={s.cardTitle}>Product-level forecast unavailable.</Text><Text style={s.muted}>The current backend provides an aggregate business forecast, not forecasts by product.</Text></View>
    <Text style={s.section}>AI Forecast Insight</Text><View style={s.insight}><Text style={s.insightText}>{forecast?.insights?.[0] ?? 'Forecast insight will appear here.'}</Text>{forecast?.insights?.slice(1).map(insight => <Text key={insight} style={s.muted}>• {insight}</Text>)}</View>
    <Text style={s.section}>What should I do?</Text><View style={s.card}><Text style={s.cardTitle}>{actionFromInsights(forecast?.insights)}</Text><Text style={s.muted}>This action is based on the current backend forecast trend.</Text></View>
    {forecast?.note && <Text style={s.disclaimer}>{forecast.note}</Text>}
  </View></ScrollView>;
}

function changeAgainstHistory(history: ForecastPoint[], future: ForecastPoint[]) { if (!future.length || history.length < future.length) return undefined; const previous = history.slice(-future.length).reduce((sum, point) => sum + point.units, 0); const expected = future.reduce((sum, point) => sum + point.units, 0); return previous ? Math.round(((expected - previous) / previous) * 1000) / 10 : undefined; }
function actionFromInsights(insights?: string[]) { const text = insights?.join(' ').toLowerCase() ?? ''; if (text.includes('upward') || text.includes('higher')) return 'Prepare stock for anticipated higher demand.'; if (text.includes('downward')) return 'Avoid over-ordering while expected demand trends downward.'; if (text.includes('stable')) return 'Maintain stock levels and monitor daily demand.'; return 'Review the forecast before placing your next stock order.'; }
function ForecastState({ children }: { children: ReactNode }) { return <ScrollView contentContainerStyle={s.page}><AppHeader title="Demand Forecast" subtitle="Plan your stock before demand arrives." /><View style={s.state}>{children}</View></ScrollView>; }
function StateMessage({ title, message, button, onPress }: { title: string; message?: string; button: string; onPress: () => void }) { return <ForecastState><Text style={s.stateTitle}>{title}</Text>{message && <Text style={s.muted}>{message}</Text>}<PrimaryButton label={button} onPress={onPress} /></ForecastState>; }
function Summary({ label, value, positive }: { label: string; value: string; positive?: boolean }) { return <View style={s.summaryItem}><Text style={s.summaryLabel}>{label}</Text><Text style={[s.summaryValue, positive && s.positive]}>{value}</Text></View>; }
function TrendChart({ historical, future }: { historical: ForecastPoint[]; future: ForecastPoint[] }) { const history = historical.slice(-7); const points = [...history.map(item => ({ ...item, kind: 'history' as const })), ...future.map(item => ({ ...item, kind: 'forecast' as const }))]; const max = Math.max(...points.map(point => point.units), 1); return <View style={s.chart}><View style={s.axis}>{points.map((point, index) => <View key={`${point.date}-${index}`} style={s.barWrap}><View style={[s.bar, point.kind === 'history' ? s.historyBar : s.futureBar, { height: Math.max(5, (point.units / max) * 110) }]} /><Text style={s.barLabel}>{point.date.slice(5)}</Text></View>)}</View></View>; }
const s = StyleSheet.create({ page: { paddingBottom: spacing.xl }, body: { paddingHorizontal: spacing.lg, gap: spacing.md }, state: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: spacing.xl, gap: spacing.md }, stateTitle: { color: colors.text, fontSize: 18, fontWeight: '800', textAlign: 'center' }, periods: { flexDirection: 'row', gap: spacing.sm }, period: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center', borderRadius: radius.sm, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface }, periodActive: { backgroundColor: colors.primary, borderColor: colors.primary }, periodText: { color: colors.muted, fontWeight: '800' }, periodTextActive: { color: '#FFF' }, summary: { backgroundColor: colors.blueSoft, padding: spacing.lg, borderRadius: radius.lg, gap: 5 }, kicker: { color: colors.primary, fontSize: 12, fontWeight: '800', letterSpacing: .7 }, bigValue: { color: colors.text, fontSize: 29, fontWeight: '800' }, summaryRows: { flexDirection: 'row', gap: spacing.md, marginTop: spacing.sm }, summaryItem: { flex: 1, gap: 4 }, summaryLabel: { color: colors.muted, fontSize: 12, fontWeight: '700', lineHeight: 16 }, summaryValue: { color: colors.text, fontSize: 16, fontWeight: '800' }, positive: { color: colors.success }, section: { color: colors.text, fontSize: 17, fontWeight: '800', marginTop: spacing.sm }, chart: { backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, padding: spacing.md, overflow: 'hidden' }, axis: { height: 140, flexDirection: 'row', alignItems: 'flex-end', gap: 3, borderBottomWidth: 1, borderColor: colors.border }, barWrap: { flex: 1, minWidth: 9, alignItems: 'center', justifyContent: 'flex-end', gap: 4 }, bar: { width: '80%', maxWidth: 18, borderRadius: 4 }, historyBar: { backgroundColor: '#A9C6FF' }, futureBar: { backgroundColor: colors.success }, barLabel: { color: colors.muted, fontSize: 8, transform: [{ rotate: '-45deg' }], marginBottom: 4 }, chartNote: { color: colors.muted, fontSize: 12, marginTop: -8 }, card: { backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, padding: spacing.md, gap: 5 }, cardTitle: { color: colors.text, fontSize: 15, fontWeight: '800' }, insight: { backgroundColor: '#EAF7F0', borderRadius: radius.md, borderWidth: 1, borderColor: '#AEDCC2', padding: spacing.md, gap: 8 }, insightText: { color: colors.text, fontSize: 16, fontWeight: '800', lineHeight: 22 }, muted: { color: colors.muted, fontSize: 13, lineHeight: 19 }, disclaimer: { color: colors.muted, fontSize: 11, lineHeight: 16, textAlign: 'center', marginTop: spacing.sm } });
